version: '3.8'

services:
  web_app:
    image: ${DOCKER_HUB_USERNAME}/task-frontend:latest  # Docker Hub tag
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - mysql_db

  mysql_db:
    image: ${DOCKER_HUB_USERNAME}/task-backend:latest   # Docker Hub tag
    build: ./backend
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: