name: CI/CD Pipeline with Docker Hub & EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/task-frontend:latest

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/task-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Git safe directory aur ownership fix
            git config --global --add safe.directory '*'

            # Agar folder pehle se hai toh ownership fix karke pull karo, warna clone karo
            if [ -d "task_manager" ]; then
              sudo chown -R $USER:$USER task_manager
              cd task_manager
              git pull origin main
            else
              git clone https://github.com/sufiyan-mujawar2006/task_manager.git
              cd task_manager
              sudo chown -R $USER:$USER .
            fi
            
            # Docker Hub se pre-built images pull karo aur containers start karo (Hyphen ke sath)
            docker-compose pull
            docker-compose up -d